# Site settings
title: "@robbiemu/handy-typescript"

# Jekyll settings
markdown: kramdown

# Extensions
plugins:
  - jekyll-paginate

# Define the first file of the documentation
default_doc: modules.md