name: tests

on:
  pull_request_target:
    branches:
      - main
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13, 19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: c-hive/gha-npm-cache@v1
    - run: npm install
    - run: npm test
